server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:spring-lab'
    username: hkjin
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8081/h2-console 접속

  kafka:
    boostrap-servers: "localhost:29092"

management:
  # 모든 정보 항상 체크
  endpoint:
    health:
      show-details: always

  # 모든 엔드포인트를 웹에 노출
  endpoints:
    web:
      exposure:
        include: "*"